name: testapp
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  cupertino_icons: ^1.0.2
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.2
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.9.1
  crypto: ^3.0.6
  excel: ^4.0.6
  video_player: ^2.9.3
  audioplayers: ^6.3.0
  flutter_gif: ^0.0.4
  mongo_dart: ^0.10.4
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png" 
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/video/
    - assets/gif/
    - assets/Cat_image/
    - assets/audio/
    - assets/team/
    - assets/img_home/
    - assets/icon/
    - assets/home_image/
    - assets/images/Andhra_Pradesh/Historical_and_Heritage_Sites/
    - assets/images/Andhra_Pradesh/Traditional_Arts_and_Crafts/
    - assets/images/Andhra_Pradesh/Culinary_Heritage/
    - assets/images/Andhra_Pradesh/Language_and_Literature/
    - assets/images/Andhra_Pradesh/Festivals_and_Cultural_Celebrations/
    - assets/images/Andhra_Pradesh/Unique_Traditions_and_Customs/
    - assets/images/Arunachal_Pradesh/Historical_and_Heritage_Sites/
    - assets/images/Arunachal_Pradesh/Traditional_Arts_and_Crafts/
    - assets/images/Arunachal_Pradesh/Culinary_Heritage/
    - assets/images/Arunachal_Pradesh/Language_and_Literature/
    - assets/images/Arunachal_Pradesh/Festivals_and_Cultural_Celebrations/
    - assets/images/Arunachal_Pradesh/Unique_Traditions_and_Customs/
    - assets/images/Assam/Historical_and_Heritage_Sites/
    - assets/images/Assam/Traditional_Arts_and_Crafts/
    - assets/images/Assam/Culinary_Heritage/
    - assets/images/Assam/Language_and_Literature/
    - assets/images/Assam/Festivals_and_Cultural_Celebrations/
    - assets/images/Assam/Unique_Traditions_and_Customs/
    - assets/images/Bihar/Historical_and_Heritage_Sites/
    - assets/images/Bihar/Traditional_Arts_and_Crafts/
    - assets/images/Bihar/Culinary_Heritage/
    - assets/images/Bihar/Language_and_Literature/
    - assets/images/Bihar/Festivals_and_Cultural_Celebrations/
    - assets/images/Bihar/Unique_Traditions_and_Customs/
    - assets/images/Chhattisgarh/Historical_and_Heritage_Sites/
    - assets/images/Chhattisgarh/Traditional_Arts_and_Crafts/
    - assets/images/Chhattisgarh/Culinary_Heritage/
    - assets/images/Chhattisgarh/Language_and_Literature/
    - assets/images/Chhattisgarh/Festivals_and_Cultural_Celebrations/
    - assets/images/Chhattisgarh/Unique_Traditions_and_Customs/
    - assets/images/Goa/Historical_and_Heritage_Sites/
    - assets/images/Goa/Traditional_Arts_and_Crafts/
    - assets/images/Goa/Culinary_Heritage/
    - assets/images/Goa/Language_and_Literature/
    - assets/images/Goa/Festivals_and_Cultural_Celebrations/
    - assets/images/Goa/Unique_Traditions_and_Customs/
    - assets/images/Gujarat/Historical_and_Heritage_Sites/
    - assets/images/Gujarat/Traditional_Arts_and_Crafts/
    - assets/images/Gujarat/Culinary_Heritage/
    - assets/images/Gujarat/Language_and_Literature/
    - assets/images/Gujarat/Festivals_and_Cultural_Celebrations/
    - assets/images/Haryana/Historical_and_Heritage_Sites/
    - assets/images/Haryana/Traditional_Arts_and_Crafts/
    - assets/images/Haryana/Culinary_Heritage/
    - assets/images/Haryana/Language_and_Literature/
    - assets/images/Haryana/Festivals_and_Cultural_Celebrations/
    - assets/images/Himachal_Pradesh/Historical_and_Heritage_Sites/
    - assets/images/Himachal_Pradesh/Traditional_Arts_and_Crafts/
    - assets/images/Himachal_Pradesh/Culinary_Heritage/
    - assets/images/Himachal_Pradesh/Language_and_Literature/
    - assets/images/Himachal_Pradesh/Festivals_and_Cultural_Celebrations/
    - assets/images/Jharkhand/Historical_and_Heritage_Sites/
    - assets/images/Jharkhand/Traditional_Arts_and_Crafts/
    - assets/images/Jharkhand/Culinary_Heritage/
    - assets/images/Jharkhand/Language_and_Literature/
    - assets/images/Jharkhand/Festivals_and_Cultural_Celebrations/
    - assets/images/Karnataka/Historical_and_Heritage_Sites/
    - assets/images/Karnataka/Traditional_Arts_and_Crafts/
    - assets/images/Karnataka/Culinary_Heritage/
    - assets/images/Karnataka/Language_and_Literature/
    - assets/images/Karnataka/Festivals_and_Cultural_Celebrations/
    - assets/images/Kerala/Historical_and_Heritage_Sites/
    - assets/images/Kerala/Traditional_Arts_and_Crafts/
    - assets/images/Kerala/Culinary_Heritage/
    - assets/images/Kerala/Language_and_Literature/
    - assets/images/Kerala/Festivals_and_Cultural_Celebrations/
    - assets/images/Madhya_Pradesh/Historical_and_Heritage_Sites/
    - assets/images/Madhya_Pradesh/Traditional_Arts_and_Crafts/
    - assets/images/Madhya_Pradesh/Culinary_Heritage/
    - assets/images/Madhya_Pradesh/Language_and_Literature/
    - assets/images/Madhya_Pradesh/Festivals_and_Cultural_Celebrations/
    - assets/images/Maharashtra/Historical_and_Heritage_Sites/
    - assets/images/Maharashtra/Traditional_Arts_and_Crafts/
    - assets/images/Maharashtra/Culinary_Heritage/
    - assets/images/Maharashtra/Language_and_Literature/
    - assets/images/Maharashtra/Festivals_and_Cultural_Celebrations/
    - assets/images/Manipur/Historical_and_Heritage_Sites/
    - assets/images/Manipur/Traditional_Arts_and_Crafts/
    - assets/images/Manipur/Culinary_Heritage/
    - assets/images/Manipur/Language_and_Literature/
    - assets/images/Manipur/Festivals_and_Cultural_Celebrations/
    - assets/images/Meghalaya/Historical_and_Heritage_Sites/
    - assets/images/Meghalaya/Traditional_Arts_and_Crafts/
    - assets/images/Meghalaya/Culinary_Heritage/
    - assets/images/Meghalaya/Language_and_Literature/
    - assets/images/Meghalaya/Festivals_and_Cultural_Celebrations/
    - assets/images/Mizoram/Historical_and_Heritage_Sites/
    - assets/images/Mizoram/Traditional_Arts_and_Crafts/
    - assets/images/Mizoram/Culinary_Heritage/
    - assets/images/Mizoram/Language_and_Literature/
    - assets/images/Mizoram/Festivals_and_Cultural_Celebrations/
    - assets/images/Nagaland/Historical_and_Heritage_Sites/
    - assets/images/Nagaland/Traditional_Arts_and_Crafts/
    - assets/images/Nagaland/Culinary_Heritage/
    - assets/images/Nagaland/Language_and_Literature/
    - assets/images/Nagaland/Festivals_and_Cultural_Celebrations/
    - assets/images/Odisha/Historical_and_Heritage_Sites/
    - assets/images/Odisha/Traditional_Arts_and_Crafts/
    - assets/images/Odisha/Culinary_Heritage/
    - assets/images/Odisha/Language_and_Literature/
    - assets/images/Odisha/Festivals_and_Cultural_Celebrations/
    - assets/images/Punjab/Historical_and_Heritage_Sites/
    - assets/images/Punjab/Traditional_Arts_and_Crafts/
    - assets/images/Punjab/Culinary_Heritage/
    - assets/images/Punjab/Language_and_Literature/
    - assets/images/Punjab/Festivals_and_Cultural_Celebrations/
    - assets/images/Rajasthan/Historical_and_Heritage_Sites/
    - assets/images/Rajasthan/Traditional_Arts_and_Crafts/
    - assets/images/Rajasthan/Culinary_Heritage/
    - assets/images/Rajasthan/Language_and_Literature/
    - assets/images/Rajasthan/Festivals_and_Cultural_Celebrations/
    - assets/images/Sikkim/Historical_and_Heritage_Sites/
    - assets/images/Sikkim/Traditional_Arts_and_Crafts/
    - assets/images/Sikkim/Culinary_Heritage/
    - assets/images/Sikkim/Language_and_Literature/
    - assets/images/Sikkim/Festivals_and_Cultural_Celebrations/
    - assets/images/Tamil_Nadu/Historical_and_Heritage_Sites/
    - assets/images/Tamil_Nadu/Traditional_Arts_and_Crafts/
    - assets/images/Tamil_Nadu/Culinary_Heritage/
    - assets/images/Tamil_Nadu/Language_and_Literature/
    - assets/images/Tamil_Nadu/Festivals_and_Cultural_Celebrations/
    - assets/images/Telangana/Historical_and_Heritage_Sites/
    - assets/images/Telangana/Traditional_Arts_and_Crafts/
    - assets/images/Telangana/Culinary_Heritage/
    - assets/images/Telangana/Language_and_Literature/
    - assets/images/Telangana/Festivals_and_Cultural_Celebrations/
    - assets/images/Tripura/Historical_and_Heritage_Sites/
    - assets/images/Tripura/Traditional_Arts_and_Crafts/
    - assets/images/Tripura/Culinary_Heritage/
    - assets/images/Tripura/Language_and_Literature/
    - assets/images/Tripura/Festivals_and_Cultural_Celebrations/
    - assets/images/Uttar_Pradesh/Historical_and_Heritage_Sites/
    - assets/images/Uttar_Pradesh/Traditional_Arts_and_Crafts/
    - assets/images/Uttar_Pradesh/Culinary_Heritage/
    - assets/images/Uttar_Pradesh/Language_and_Literature/
    - assets/images/Uttar_Pradesh/Festivals_and_Cultural_Celebrations/
    - assets/images/Uttarakhand/Historical_and_Heritage_Sites/
    - assets/images/Uttarakhand/Traditional_Arts_and_Crafts/
    - assets/images/Uttarakhand/Culinary_Heritage/
    - assets/images/Uttarakhand/Language_and_Literature/
    - assets/images/Uttarakhand/Festivals_and_Cultural_Celebrations/
    - assets/images/West_Bengal/Historical_and_Heritage_Sites/
    - assets/images/West_Bengal/Traditional_Arts_and_Crafts/
    - assets/images/West_Bengal/Culinary_Heritage/
    - assets/images/West_Bengal/Language_and_Literature/
    - assets/images/West_Bengal/Festivals_and_Cultural_Celebrations/
    - assets/icon/
    